version: "3"
services:
  reverse-proxy:
    image: traefik:latest
    command:
      - --api.dashboard=true
      - --providers.docker
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:z
    restart: unless-stopped
    privileged: true
    labels:
      - "traefik.http.routers.dashboard.rule=Host(`${SERVER}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.service=api@internal"

  gameserver:
    build: .
    volumes:
      - .:/project:z
    restart: unless-stopped
    tty: true
    labels:
      - "traefik.http.routers.gameserver.rule=PathPrefix(`/game`)"
      - "traefik.http.services.gameserver.loadbalancer.server.port=${GAMEPORT}"

  webserver:
    image: nginx:latest
    volumes:
      - ./game:/usr/share/nginx/html:z
    restart: unless-stopped
    labels:
      - "traefik.http.routers.webserver.rule=PathPrefix(`/`)"
      - "traefik.http.services.webserver.loadbalancer.server.port=${WEBPORT}"
