version: "3.9"
services:
  export:
    image: "ioribranford/godot-docker:3.2.3"
    volumes:
      - .:/project
    command: godot --quiet --export HTML5 ../game/pixeltanks.html project/src/project.godot
    profiles:
      - export
  gameserver:
    build: .
    environment:
      - SERVER
      - GAMEPORT
    ports:
      - "${GAMEPORT}:${GAMEPORT}"
      - "${GAMEPORT}:${GAMEPORT}/udp"
    volumes:
      - .:/project
    tty: true
    restart: unless-stopped
    profiles:
      - run
  webserver:
    image: nginx:latest
    volumes:
      - ./game:/usr/share/nginx/html
    ports:
      - "${WEBPORT}:80"
    restart: unless-stopped
    profiles:
      - run
